name = "test-qpzmqpg"
type = "javascript"

workers_dev = true

[env.production]
workers_dev = false


[[d1_databases]]
binding = "DB" # This will be how you refer to your database in your Worker
database_name = "qpzmqpg-db"
database_id = "4db9d921-42f7-40f2-bdcf-bcef5ee501c6"

